### ISSUE TITLE
Npc no encontrado "En busca de la Compañía Bravo"

### ISSUE THREAD

**Issue by kael-mj** [searum/ColossusWoW-Legion-Bugtracker#12]
No esta el npc para poder entregar la misión.
http://es.wowhead.com/npc=43270/messner
http://es.wowhead.com/quest=26586/en-busca-de-la-compania-bravo

**Comment by Ragebones** [comment]
El npc si se encuentra en el servidor, se ha corregido la quest para que se complete y puedas seguir con la siguiente.

**Comment by searum** [comment]
fix
