### ISSUE TITLE
Fallo de reputación ventormenta 

### ISSUE THREAD

**Issue by kael-mj** [searum/ColossusWoW-Legion-Bugtracker#5]
las misiones de "bosque de elwynn" no están dando reputación (todas las misiones del lugar no dan reputación)

**Comment by tomasgx** [comment]
no es solo ventormenta me he creado otros pj de diferentes razas y todas tienen el mismo problema, ninguna ganan reputacion ni con su raza, ni con el resto de su faccion.

**Comment by searum** [comment]
deberia de funcionar ya, si no funciona todavia entonces reporta la misión porque no es un problema generalizado.

**Comment by tomasgx** [comment]
como dije es un proble con la reputacion que tengo pj de otras razas ademas de la humana y aun no gano reputacion

juge con un pj hoy 5/10/2016 y aun no dan reputacion 
Raza: NO-Muerto
Clase: Guerrero

las misiones que hice que no me dieron repu son las del inicio 
primera
http://es.wowhead.com/quest=26799/aquellos-que-no-pudieron-salvarse
segunda
http://es.wowhead.com/quest=28652/custodio-caice

ppostearia otras pero no se que le paso a el wowhead en mi pc que entro a una paguina y me redirecciona enceguida a una publicidad. pero con esas 2 creo que pueden verificar
