### ISSUE TITLE
Bug maestro de grifos "Zaldaan"

### ISSUE THREAD

**Issue by kael-mj** [searum/ColossusWoW-Legion-Bugtracker#6]
no muestra las tuas de vuelo -  ni tampoco se puede usar para usar vuelo
http://es.wowhead.com/npc=43991/zaldaan

**Comment by tomasgx** [comment]
recomiendo revisar todos los maestros de grifo ya que algunos funcionan y otros no, (algunos si muestan el mapa con las rutas de vuelo, pero otros no muestran nada). ya he visto varios asi que el problema es global.

**Comment by searum** [comment]
Podriais facilitarnos la tarea ya que vosotros pasais más amenudo por esas zonas pues podriais descargar el addon idtip y con ese addon targeteas al npc y te dice la ID y nos la pones aqui... asi lo reparo al instante

**Comment by searum** [comment]
fix
